### ISSUE TITLE
[Client] Home Page

### ISSUE THREAD

**Issue by k-lombard** [k-lombard/TutorCare-JIA-1307#4]
- Create a home page with proper figma theme that conveys our vision statement, purpose, and core values. 
 - Responsive design that is mobile friendly. This should be verified using chrome developer tools.
 - Also make navbar responsive.

**Comment by k-lombard** [comment]
<img width="1440" alt="homepage" src="https://user-images.githubusercontent.com/59323055/148007128-5a68e362-6563-4c9d-b342-cc18ab96b310.png">

**Comment by christophrrb** [comment]
Looks nice! I just think we should change the font for "Join a community of parents and students". I can do it by tomorrow if that's okay.

**Comment by k-lombard** [comment]
> Looks nice! I just think we should change the font for "Join a community of parents and students". I can do it by tomorrow if that's okay.

Yeah sure we just gotta choose a good font
